In [1]:
import scipy as sp

scipy.linalg    

scipy.special

spicy.integrate

scipy.optimize

scipy.interpolate

scipy.fftpack

scipy.signal - sinyal işlemek için

scipy.spatial 

scipy.stats

scipy.ndimage

scipy.io

scipy.constants - matematiksel ve fiziksel sabitleri 
yazabilmek için

scipy.sparse    



In [2]:
import numpy as np
from scipy import linalg 


In [3]:
A = np.array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


In [4]:
B=linalg.inv(A)
print(B)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [5]:
A = np.array([[1,3,5],[2,5,1],[2,3,8]])
B = np.array([[10],[8],[3]])


In [9]:
print(linalg.inv(A).dot(B))

[[-9.28]
 [ 5.16]
 [ 0.76]]


In [10]:
print(np.linalg.solve(A,B))

[[-9.28]
 [ 5.16]
 [ 0.76]]


In [16]:
from scipy.linalg import lu
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Matris =>\n',A)
P, L, U = lu(A)
print('\n',P)
print('\n',L)
print('\n',U)
#yeniden birleştirme
B = P.dot(L).dot(U)
print('\n',B)

Matris =>
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]

 [[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]

 [[7.         8.         9.        ]
 [0.         0.85714286 1.71428571]
 [0.         0.         0.        ]]

 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [17]:
#integral
from scipy import integrate
x2 = lambda x : x**2
I =integrate.quad(x2,0,6)
print(I)

(72.00000000000001, 7.993605777301129e-13)


In [19]:
import scipy.integrate as integrate
import scipy.special as special

#jv(2.5, x)
result = integrate.quad(lambda x : special.jv(2.5,x), 0, 5)
print(result)

(1.2711856058069952, 1.1793280599040403e-08)


In [20]:
from scipy.misc import derivative

def turev(x):
    return x**3 + x**2

D = derivative(turev, 1.0, dx = 1e-6)
print(D)

4.999999999921734


In [23]:
from scipy.misc import derivative

Turev = (lambda x : x**3 + x**2 + 2*x)

D = derivative((lambda x : x**3 + x**2 + 2*x), 1.0, dx = 1e-6)
print(D)

6.999999999868223


In [24]:
from scipy import stats
from scipy.stats import norm

In [25]:
#describe
norm.cdf(0)

0.5

In [26]:
norm.cdf([-1., 0, 1])

array([0.15865525, 0.5       , 0.84134475])