In [3]:
import tensorflow as tf
import numpy as np

In [4]:
matrix1 = np.array([(2,2,2),(2,2,2),(2,2,2)], dtype = 'int32')
matrix2 = np.array([(1,1,1),(1,1,1),(1,1,1)], dtype = 'int32')
print(matrix1)
print(matrix2)

matrix1 = tf.constant(matrix1)
matrix2 = tf.constant(matrix2)
matrix_product = tf.matmul(matrix1,matrix2)
matrix_sum = tf.add(matrix1,matrix2)

matrix3 = np.array([(2,7,2),(1,4,2),(9,0,2)], dtype = 'float32')
print(matrix3)
matrix_det = tf.matrix_determinant(matrix3)

with tf.compat.v1.Session() as sess:
    result1=sess.run(matrix_product)
    result2=sess.run(matrix_sum)
    result3=sess.run(matrix_det)

print(result1)
print(result2)
print(result3)

[[2 2 2]
 [2 2 2]
 [2 2 2]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[2. 7. 2.]
 [1. 4. 2.]
 [9. 0. 2.]]


AttributeError: module 'tensorflow' has no attribute 'matrix_determinant'

In [5]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

data=['cold','cold','warm','cold','hot','warm','cold','warm','hot']
values = np.array(data)
print(values)

#integer encoding
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)

['cold' 'cold' 'warm' 'cold' 'hot' 'warm' 'cold' 'warm' 'hot']
[0 0 2 0 1 2 0 2 1]


In [6]:
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded),1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [8]:
from numpy import argmax
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0,:])])
print(inverted)

['cold']


In [ ]:
#tensorflow ile SLP (tek katmanlı algılayıcı)

In [ ]:
#for tf1
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("data",one_hot = True)

#parametreler
learning_rate = 0.01
training_epoch = 25
batch_size = 100
display_step = 1

x = tf.placeholder("float", [None, 784])
y = tf.placeholder("float", [None, 10])

W = tf.Variable(tf.zeros([784, 10]))
b = tf.Variable(tf.zeros([10]))

activation = tf.nn.softmax(tf.matmul(x, W) + b)
